const url = 'https://santic.netlify.app/public/assets/img-icons/';

export const tools = [
  { name: "Java", icon: url + "java.png" },
  { name: "C#", icon: url + "c1.png" },
  { name: "JavaScript", icon: url + "javascript.png" },
  { name: "Python", icon: url + "python-original.213x256.png" },
  { name: "WordPress", icon: url + "wordpress.png" },
  { name: "Angular", icon: url + "angular.png" },
  { name: "React", icon: url + "react.png" },
  { name: "Ionic", icon: url + "ionic.png" },
  { name: "Kali Linux", icon: url + "kali.png" },
  { name: "Linux", icon: url + "linux.png" },
  { name: "Windows", icon: url + "microsoft.png" },
  { name: "Android Studio", icon: url + "android.png" },
  { name: "Oracle", icon: url + "oracle.png" },
  { name: "PHP", icon: url + "php.256x256.png" },
  { name: "Ruby", icon: url + "ruby.png" },
  { name: "Node", icon: url + "node.png" },
  { name: "Figma", icon: url + "figma.png" },
  { name: "Adobe Illustrator", icon: url + "ai.png" },
  { name: "Adobe Photoshop", icon: url + "ps.png" },
  { name: "Adobe XD", icon: url + "xd.png" },
  { name: "Git y GitHub", icon: url + "github.png" },
  { name: "MongoDB", icon: url + "mongo.png" },
  { name: "MySQL", icon: url + "mysql.png" },
  { name: "SQL", icon: url + "sql.png" },
  { name: "Spring Boot", icon: url + "spring.png" },
  { name: "Vuetify", icon: url + "vuetify.png" },
  { name: "Tailwind", icon: url + "tailwind.png" },
  { name: "Postgres", icon: url + "postgres.png" },
  { name: "Blender", icon: url + "blender.png" },
  { name: "Java", icon: url + "java.png" },
  { name: "C#", icon: url + "c1.png" },
  { name: "JavaScript", icon: url + "javascript.png" },
  { name: "Python", icon: url + "python-original.213x256.png" },
  { name: "WordPress", icon: url + "wordpress.png" },
  { name: "Angular", icon: url + "angular.png" },
  { name: "React", icon: url + "react.png" },
  { name: "Ionic", icon: url + "ionic.png" },
  { name: "Kali Linux", icon: url + "kali.png" },
  { name: "Linux", icon: url + "linux.png" },
  { name: "Windows", icon: url + "microsoft.png" },
  { name: "Android Studio", icon: url + "android.png" },
  { name: "Oracle", icon: url + "oracle.png" },
  { name: "PHP", icon: url + "php.256x256.png" },
  { name: "Ruby", icon: url + "ruby.png" },
  { name: "Node", icon: url + "node.png" },
  { name: "Figma", icon: url + "figma.png" },
  { name: "Adobe Illustrator", icon: url + "ai.png" },
  { name: "Adobe Photoshop", icon: url + "ps.png" },
  { name: "Adobe XD", icon: url + "xd.png" },
  { name: "Git y GitHub", icon: url + "github.png" },
  { name: "MongoDB", icon: url + "mongo.png" },
  { name: "MySQL", icon: url + "mysql.png" },
  { name: "SQL", icon: url + "sql.png" },
  { name: "Spring Boot", icon: url + "spring.png" },
  { name: "Vuetify", icon: url + "vuetify.png" },
  { name: "Tailwind", icon: url + "tailwind.png" },
  { name: "Postgres", icon: url + "postgres.png" },
  { name: "Blender", icon: url + "blender.png" }
];
